# DockerFile for C3D container
FROM kunalg106/cuda100

# Use a Bionic base image
# FROM python:3

# Install common software
# RUN apt-get update 
# RUN apt-get install -y software-properties-common
# RUN apt-get install -y build-essential
# RUN apt-get install -y git && \
#    apt-get install -y vim && \
#    apt-get install -y wget && \
#    apt-get install -y sudo && \
#    apt-get install -y libblas-dev && \
#    apt-get install -y liblapack-dev

# New user
RUN useradd -m -p c3dpwd -g sudo c3duser

# Install C3D
RUN wget -P /home/c3duser 'https://sourceforge.net/projects/c3d/files/c3d/Nightly/c3d-nightly-Linux-gcc64.tar.gz'
RUN cd /home/c3duser/ && \
    tar -xf /home/c3duser/c3d-nightly-Linux-gcc64.tar.gz
RUN cp -a home/c3duser/c3d-1.1.0-Linux-gcc64/bin/. /usr/local/bin

# Install other packages
RUN pip install nibabel && \
    pip install pandas

# Change user
USER c3duser
WORKDIR /home/c3duser

# Add files
ADD *.py /home/c3duser/